apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    k8s-app: nginx-ds
spec:
  selector:
    matchLabels:
      name: nginx-rs
  template:
    metadata:
      labels:
        name: nginx-rs
    spec:
      containers:
      - name: nginx-rs-ctr
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
