apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"nginx-ds"},"name":"nginx-ds","namespace":"default"},"spec":{"selector":{"matchLabels":{"name":"nginx-rs"}},"template":{"metadata":{"labels":{"name":"nginx-rs"}},"spec":{"containers":[{"image":"nginx","name":"nginx-rs-ctr","resources":{"limits":{"memory":"200Mi"},"requests":{"cpu":"100m","memory":"200Mi"}}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: nginx-ds
  name: nginx-ds
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/nginx-ds
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nginx-rs
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nginx-rs
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-rs-ctr
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 3
  updateStrategy:
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
